version: "3.7"

networks:
  proxy:
    external: true
  task_manager:

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - task_manager
      - proxy

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - task_manager

  node:
    image: node:latest
    restart: unless-stopped
    ports:
        - "5173:5173"
    working_dir: /var/www/
    volumes:
        - ./:/var/www
    networks:
        - task_manager
    command: 'npm run dev'

